### ISSUE TITLE
Arch Linux Announcement Tracker (ongoing)

### ISSUE THREAD

**Issue by bunnicash** [bunnicash/archinstall#1]
# Keeping track of announcements for updates to the Arch system:

Arch Linux is a rolling release distribution, changes to how the system functions and how it's installed are listed here.

- [x] https://archlinux.org/news/undone-replacement-of-pipewire-media-session-with-wireplumber/ (Not affected)
- [x] https://archlinux.org/news/qemu-700-changes-split-package-setup/ (Fixed)
- [x] https://archlinux.org/news/keycloak-1701-2-update-requires-manual-reconfiguration/ (No action needed)
